"""initial schema

Revision ID: 767f9927efb0
Revises:
Create Date: 2026-07-28 06:38:08.115155+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "767f9927efb0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commodities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_slug", sa.String(length=128), nullable=False),
        sa.Column("group", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("specification", sa.String(length=255), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commodities")),
        sa.UniqueConstraint("canonical_slug", name=op.f("uq_commodities_canonical_slug")),
    )
    op.create_table(
        "regions",
        sa.Column("psgc_code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "region",
                "province",
                "municipality",
                "city",
                name="region_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("psgc_code", name=op.f("pk_regions")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("robots_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("robots_allowed", sa.Boolean(), nullable=True),
        sa.Column("licence", sa.String(length=255), nullable=True),
        sa.Column("attribution_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("slug", name=op.f("uq_sources_slug")),
    )
    op.create_table(
        "commodity_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_name", sa.String(length=255), nullable=False),
        sa.Column("commodity_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodities.id"],
            name=op.f("fk_commodity_aliases_commodity_id_commodities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commodity_aliases")),
        sa.UniqueConstraint("raw_name", name=op.f("uq_commodity_aliases_raw_name")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "failed",
                "partial",
                name="ingestion_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("files_seen", sa.Integer(), server_default="0", nullable=False),
        sa.Column("files_fetched", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rows_upserted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rows_quarantined", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_ingestion_runs_finished_after_started"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_ingestion_runs_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        "ix_ingestion_runs_source_id_started_at",
        "ingestion_runs",
        ["source_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "markets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region_psgc_code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("municipality", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_psgc_code"],
            ["regions.psgc_code"],
            name=op.f("fk_markets_region_psgc_code_regions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
        sa.UniqueConstraint(
            "region_psgc_code",
            "municipality",
            "name",
            name=op.f("uq_markets_region_psgc_code_municipality_name"),
        ),
    )
    op.create_table(
        "quarantine",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "index",
                "parse",
                "alias",
                "validate",
                name="quarantine_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_file_sha256", sa.String(length=64), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_quarantine_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarantine")),
    )
    op.create_index(
        "ix_quarantine_source_file_sha256", "quarantine", ["source_file_sha256"], unique=False
    )
    op.create_index(
        "ix_quarantine_stage_created_at", "quarantine", ["stage", "created_at"], unique=False
    )
    op.create_table(
        "price_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("commodity_id", sa.Integer(), nullable=False),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("low", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("high", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("prevailing", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("average", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unavailable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("revision_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column("source_file_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT unavailable OR (low IS NULL AND high IS NULL AND prevailing IS NULL AND average IS NULL)",
            name=op.f("ck_price_observations_unavailable_implies_no_prices"),
        ),
        sa.CheckConstraint(
            "low IS NULL OR high IS NULL OR low <= high",
            name=op.f("ck_price_observations_low_not_above_high"),
        ),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodities.id"],
            name=op.f("fk_price_observations_commodity_id_commodities"),
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["markets.id"], name=op.f("fk_price_observations_market_id_markets")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_price_observations_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_observations")),
        sa.UniqueConstraint(
            "source_id",
            "market_id",
            "commodity_id",
            "observed_on",
            name="uq_price_observations_natural_key",
        ),
    )
    op.create_index(
        "ix_price_observations_commodity_observed_on",
        "price_observations",
        ["commodity_id", "observed_on"],
        unique=False,
    )
    op.create_index(
        "ix_price_observations_observed_on", "price_observations", ["observed_on"], unique=False
    )
    op.create_table(
        "observation_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("low", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("high", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("prevailing", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("average", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unavailable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("source_file_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "superseded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["price_observations.id"],
            name=op.f("fk_observation_revisions_observation_id_price_observations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation_revisions")),
        sa.UniqueConstraint(
            "observation_id",
            "revision_no",
            name=op.f("uq_observation_revisions_observation_id_revision_no"),
        ),
    )
    op.create_index(
        "ix_observation_revisions_observation_id",
        "observation_revisions",
        ["observation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_observation_revisions_observation_id", table_name="observation_revisions")
    op.drop_table("observation_revisions")
    op.drop_index("ix_price_observations_observed_on", table_name="price_observations")
    op.drop_index("ix_price_observations_commodity_observed_on", table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_index("ix_quarantine_stage_created_at", table_name="quarantine")
    op.drop_index("ix_quarantine_source_file_sha256", table_name="quarantine")
    op.drop_table("quarantine")
    op.drop_table("markets")
    op.drop_index("ix_ingestion_runs_source_id_started_at", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_table("commodity_aliases")
    op.drop_table("sources")
    op.drop_table("regions")
    op.drop_table("commodities")
    # ### end Alembic commands ###
